services:
  stremio-server:
    image: stremio/server:latest
    container_name: stremio-server
    ports:
      - "11470:11470"
    environment:
      - NO_CORS=1
    volumes:
      - ./data:/root/.stremio-server